/**
 * Test script for Kling 2.6 Video Generation API
 * Run with: KIE_API_KEY=your_key npx tsx src/lib/kie/test-kling-2.6.ts
 */

import {
  createKling26Client,
  ASPECT_RATIOS,
  DURATIONS,
  type TaskState,
} from "./kling-2.6";

const API_KEY = process.env.KIE_API_KEY || "";

async function runTests() {
  console.log("=== Testing Kling 2.6 Video Generation API ===\n");

  if (!API_KEY) {
    console.error("Error: KIE_API_KEY environment variable is required");
    console.log(
      "Usage: KIE_API_KEY=your_key npx tsx src/lib/kie/test-kling-2.6.ts"
    );
    process.exit(1);
  }

  const client = createKling26Client(API_KEY);

  console.log("Available options:");
  console.log("  Aspect Ratios:", ASPECT_RATIOS.join(", "));
  console.log("  Durations:", DURATIONS.map((d) => `${d}s`).join(", "));
  console.log();

  // Test 1: Text-to-Video
  console.log("--- Test 1: Text-to-Video (5s, 16:9) ---");
  try {
    const result = await client.generateTextToVideo(
      {
        prompt:
          "A cute orange cat playing with a ball of yarn, cinematic lighting",
        sound: true,
        aspect_ratio: "16:9",
        duration: "5",
      },
      {
        pollInterval: 5000,
        maxAttempts: 120,
        onStateUpdate: (state: TaskState) => {
          process.stdout.write(`\r  State: ${state}   `);
        },
      }
    );

    console.log("\n  SUCCESS!");
    console.log("  Task ID:", result.task.data?.taskId);
    console.log("  Cost time:", result.task.data?.costTime, "ms");
    console.log("  Result URLs:", result.output?.resultUrls);
  } catch (error) {
    console.error("\n  FAILED:", error);
  }

  // Test 2: Image-to-Video (using a kie.ai generated image)
  console.log("\n--- Test 2: Image-to-Video (5s) ---");
  try {
    // Use an image generated by Nano Banana Pro (kie.ai hosted)
    const result = await client.generateImageToVideo(
      {
        prompt: "The cat slowly turns its head and blinks",
        image_urls: [
          "https://tempfile.aiquickdraw.com/g/fd00abdce58019cd9ba86b86a53fd752_1765821358.png",
        ],
        sound: false,
        duration: "5",
      },
      {
        pollInterval: 5000,
        maxAttempts: 120,
        onStateUpdate: (state: TaskState) => {
          process.stdout.write(`\r  State: ${state}   `);
        },
      }
    );

    console.log("\n  SUCCESS!");
    console.log("  Task ID:", result.task.data?.taskId);
    console.log("  Cost time:", result.task.data?.costTime, "ms");
    console.log("  Result URLs:", result.output?.resultUrls);
  } catch (error) {
    console.error("\n  FAILED:", error);
  }

  console.log("\n=== All tests completed ===");
}

runTests();
